import { Cinzel_Decorative as FontSans } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from '@/components/theme-provider'

import { cn } from '@/lib/utils'

export const fontSans = FontSans({
  subsets: ['latin']
  , variable: '--font-sans',
  weight: '400'
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn("min-h-screen bg-background font-sans antialiased tracking-wider",
        fontSans.variable)}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enabledSystem
          disableTransitionOnChange
        >{children}</ThemeProvider>
      </body>
    </html>
  )
}
